version: "3"

services:
  api:
    build: api
    ports:
      - "5115:5115"
    depends_on:
      - db
  db:
    build: db 
    ports:
      - "6379:6379"
    volumes:
      - .data:/data